---

# CIS 1.5.1
- name: Disable coredump storage
  blockinfile:
    path: /etc/systemd/coredump.conf.d/coredump_hardening.conf
    create: yes
    block: |
      [Coredump]
      Storage=none
    owner: 'root'
    group: 'root'
    mode: '0600'

# CIS 1.1.2
# STIG 021340
- name: "Ensure separate partition exists for /tmp"
  systemd:
    name: tmp.mount
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started

# CIS 1.1.7
- name: "Ensure separate partition exists for /var/tmp"
  mount:
    name: /var/tmp
    src: /tmp
    state: mounted
    fstype: tmpfs

- name: Get mounts from /etc/mtab - nodev
  command: cat /etc/mtab
  changed_when: no
  register: mount_options

# CIS 1.1.14
- name: "Ensure separate partition exists for /dev/shm"
  mount:
    name: /dev/shm
    src: tmpfs
    state: mounted
    fstype: tmpfs

# CIS 1.1.3
# CIS 1.1.8
# CIS 1.1.15
- name: Ensure fstab uses nodev
  mount:
    path: "{{ item.split(' ')[1] }}"
    state: mounted
    fstype: "{{ item.split(' ')[2] }}"
    src: "{{ item.split(' ')[0] }}"
    opts: "{{ item.split(' ')[3].split(',') | union(['nodev']) | unique | join(',') }}"
  with_items: "{{ mount_options.stdout_lines }}"
  when:
    - item.split(" ")[1] in  ["/boot" , "/dev/shm", "/home", "/tmp", "/var", "/var/tmp", "/var/log", "/proc"]

- name: Get mounts from /etc/mtab - noexec
  command: cat /etc/mtab
  changed_when: no
  register: mount_options

# CIS 1.1.4
# CIS 1.1.9
# CIS 1.1.16
- name: Ensure fstab uses nosuid
  mount:
    path: "{{ item.split(' ')[1] }}"
    state: mounted
    fstype: "{{ item.split(' ')[2] }}"
    src: "{{ item.split(' ')[0] }}"
    opts: "{{ item.split(' ')[3].split(',') | union(['nosuid']) | unique | join(',') }}"
  with_items: "{{ mount_options.stdout_lines }}"
  when:
    - item.split(" ")[1] in ["/boot" , "/dev/shm", "/tmp", "/var", "/var/tmp", "/var/log", "/proc"]

- name: Get mounts from /etc/mtab - nosuid
  command: cat /etc/mtab
  changed_when: no
  register: mount_options

# CIS 1.1.5
# CIS 1.1.10
# CIS 1.1.17
- name: Ensure fstab uses noexec
  mount:
    path: "{{ item.split(' ')[1] }}"
    state: mounted
    fstype: "{{ item.split(' ')[2] }}"
    src: "{{ item.split(' ')[0] }}"
    opts: "{{ item.split(' ')[3].split(',') | union(['noexec']) | unique | join(',') }}"
  with_items: "{{ mount_options.stdout_lines }}"
  when:
    - item.split(" ")[1] in ["/boot" , "/dev/shm", "/tmp", "/var", "/var/tmp", "/var/log", "/proc"]

- name: Set option hidepid for proc filesystem
  mount:
    path: /proc
    src: proc
    fstype: proc
    opts: '{{ proc_mnt_options }}'
    state: present

...
