---

aide_package: 'aide'
auditd_package: 'audit'
modprobe_package: 'kmod'

disable_root_user: yes

os_auditd_max_log_file: 6
os_auditd_max_log_file_action: keep_logs
os_auth_allow_homeless: no
os_auth_gid_min: 1000
os_auth_lockout_time: 600  # 10min
os_auth_pam_passwdqc_enable: yes
os_auth_pw_max_age: 60
os_auth_pw_min_age: 7  # discourage password cycling
os_auth_retries: 5
os_auth_sys_gid_max: 999
os_auth_sys_gid_min: 100
os_auth_sys_uid_max: 999
os_auth_sys_uid_min: 100
os_auth_timeout: 60
os_auth_uid_min: 1000
os_env_extra_user_paths: []
os_env_umask: '027'

pam_faillock_unlock_time: '0'
pam_faillock_fail_interval: '900'
pam_faillock_deny: '3'
pam_faillock_fail_for_root: yes

proc_mnt_options: 'rw,nosuid,nodev,noexec,relatime,hidepid=2'

# CIS 2.2.1.1
# CIS 2.2.1.2
# STIG 010090
wanted_pkg:
  - chrony

# CIS 2.2.3
# CIS 2.2.4
# CIS 2.2.6
# CIS 2.2.7
# CIS 2.2.9
# CIS 2.2.12
# CIS 2.2.17
# CIS 2.2.18
# CIS 2.2.19
# STIG 021300
unwanted_services:
  - avahi-daemon.service
  - cups.service
  - kdump.service
  - nfs.service
  - rexec.socket
  - rlogin.socket
  - rsh.socket
  - slapd.service
  - smb.service
  - telnet.service
  - tftp.service
  - vsftpd.service

# CIS 1.6.1.4
# CIS 1.6.1.5
# CIS 2.1.1
# CIS 2.1.2
# CIS 2.1.3
# CIS 2.1.4
# CIS 2.1.5
# CIS 2.1.6
# CIS 2.1.7
# CIS 2.3.1
# CIS 2.3.2
# CIS 2.3.4
# STIG 020000
# STIG 020010
# STIG 021710
# STIG 040690
# STIG 040700
unwanted_pkg:
  - mcstrans
  - rsh
  - rsh-server
  - setroubleshoot
  - telnet-server
  - tftp
  - tftp-server
  - xinetd
  - ypserv

kernel_packages:
  - kernel
  - kernel-headers
  - kernel-devel

# disable unused filesystems
os_unused_filesystems:
  - "cramfs"    # CIS 1.1.1.1
  - "freevxfs"  # CIS 1.1.1.2
  - "jffs2"     # CIS 1.1.1.3
  - "hfs"       # CIS 1.1.1.4
  - "hfsplus"   # CIS 1.1.1.5
  - "squashfs"  # CIS 1.1.1.6
  - "udf"       # CIS 1.1.1.7
  - "vfat"      # CIS 1.1.1.8
  - "dccp"      # CIS 3.5.1 STIG 020101
  - "sctp"      # CIS 3.5.2
  - "rds"       # CIS 3.5.3
  - "tipc"      # CIS 3.5.4

# STIG 020100
os_unused_modules:
  - "usb-storage"

os_filesystem_whitelist:
  - "ext4"
  - "xfs"

ssh_ciphers: "aes128-ctr,aes192-ctr,aes256-ctr"
ssh_MACs: "hmac-sha2-512,hmac-sha2-256"
ssh_key_algorithms: "curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"
ssh_max_startups: "10:30:100"
ssh_max_sessions: 10
ssh_root_login: "no"  # prohibit-password

shell_timeout_sec: 900

...
